# Generated by Django 5.0.6 on 2024-05-23 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cart_product_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_big',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Изображение большое'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_min',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Изображение мини'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000000)], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(height_field=100, upload_to='products/categorys/', verbose_name='Изображение', width_field=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=100, upload_to='products/', verbose_name='Изображение', width_field=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(height_field=100, upload_to='products/subcategorys/', verbose_name='Изображение', width_field=100),
        ),
    ]
