# Generated by Django 5.0.6 on 2024-05-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_big_product_image_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_big',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение большое'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_min',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение мини'),
        ),
    ]
