# Generated by Django 5.0.6 on 2024-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image_big_alter_product_image_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_big',
            field=models.ImageField(blank=True, default='image_min', upload_to='products/', verbose_name='Изображение большое'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_min',
            field=models.ImageField(blank=True, default='image_min', upload_to='products/', verbose_name='Изображение мини'),
        ),
    ]
