# Generated by Django 5.0.6 on 2024-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_product_cart_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_big',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='Изображение'),
        ),
    ]
